### ISSUE TITLE
Peaks found do not correspond to plot

### ISSUE THREAD

**Issue by YanaVassileva** [GuanLab/FastClone_GuanLab#11]
Hey, 

I was very happy about how easy to use your tool is. I have just few questions. When I run the analysis (after adjusting the iterations to 20000 and   kde.covariance_factor = lambda: .05) I get following output:
 `[2021-08-08 08:03:24.157845] INFO: fastclone.subclone: Found peaks: [0.299711056385342, 0.5461652289290958, 0.8620634268209779, 0.9489925214881291, 0.999999482814359]
[2021-08-08 08:03:24.157986] INFO: fastclone.subclone: Adjusted peaks to: [0.299711056385342, 0.5461652289290958, 0.8620634268209779, 0.9489925214881291, 0.999999482814359]
[2021-08-08 08:04:06.340673] INFO: fastclone.subclone: EM is fully converged.
[2021-08-08 08:04:15.983586] INFO: fastclone.subclone: EM is fully converged.`

I concluded that I should expect 5 subclones, as 5 peaks were found. However, the phylogeny tree shows just 2 subclones. 

I wanted to also make a similar plot to the one, which you had in your paper (see below), representing how heterogenious my sample is. Lets assume I have 3 clones with proportions [0:0.99, 1:0.2, 2: 0.4], where subclone 1 and 2 both originate from 0. Can I just say that the proportions of cells with mutations from cluster 0: 0.399, proportions of cells with mutations from cluster 0+1: 0.2, proportions of cells with mutations from cluster 0+2: 0.4. Would that be correct?

![Tumour_heterogeneity](https://user-images.githubusercontent.com/73296702/128625593-7895dbeb-d082-4d32-8095-909c757bf651.JPG)

I would be very, very happy about an answer!

Best regards, 
Yana Vassileva

**Comment by Yaoyx** [comment]
Hi Yana,

Thank you for using FastClone. Regarding your first question, adjusted peaks are not the final result. Once FastClone gets the adjusted peaks, it will assign SNVs to peaks, and the final peaks are validated by the step of SNV assignments--any peaks with less than 10 SNVs will be discarded, and Fastclone will redo the assignments based on the left peaks. Hence, please check whether the "subclone.csv" file has the same result as the phylogeny plot or not. In your case, I guess these three peaks, "0.8620634268209779, 0.9489925214881291, 0.999999482814359", are likely to be discarded.

Regarding your second question, generally say yes. Subclones should contain their parent clones' mutations and new mutations.

I hope this answers your questions, and please let me know if you have any other questions.

P.S. I updated the plot function a month ago, please check if you have the latest version of FastClone.

**Comment by YanaVassileva** [comment]
Hey, 

Thank you a lot for the fast response. I am using the latest version. By saying that you have updated the plotting function, I assume that there should be a function producing the output which I desire (something like the plot below or at least the proportions).

![](https://user-images.githubusercontent.com/73296702/128625593-7895dbeb-d082-4d32-8095-909c757bf651.JPG)

I get till now only the phylogeny tree (which is correct according to the description)... but I can calculate the proportions myself, as discussed before:

![example_phylogeny](https://user-images.githubusercontent.com/73296702/129013132-6c99f6c0-31b6-4d73-817b-1374c1cd91d9.png)

Thank you a lot!
Best, 
Yana

**Comment by Yaoyx** [comment]
Hey Yana,

The first figure you referred to is a biological diagram for explaining the concept of tumor heterogeneity only, and it was drawn manually via Adobe Illustrator. 

Regarding the "proportion" you mention, I add some codes to output a file called "phylogeny_proportions.csv", which gives you the proportion of a subclone in its parent clone.

Try the 1.0.9 version of FastClone, and let me know if it meets what you want.

Regards
Yao
