### ISSUE TITLE
Battenberg input file issue

### ISSUE THREAD

**Issue by ranjit58** [GuanLab/FastClone_GuanLab#12]
Hello,
As I understand, to run fastclone, first we have to create input files using batterberg. However, I am not able to get battenberg tool to work. Do you have any suggestion (docker container, example files etc) regarding installing or running it?

**Comment by Yaoyx** [comment]
Hello,

FastClone also accepts pyclone-format files. I am not sure what problem you encountered, but you might find the solution on their GitHub page [https://github.com/Wedge-lab/battenberg](url).
