### ISSUE TITLE
Target sequence data as input

### ISSUE THREAD

**Issue by wt12318** [GuanLab/FastClone_GuanLab#13]
Hi,
I have mutations and cnv data from target panel sequence. Can I use Fastclone to get subclones?
Thanks!

**Comment by Yaoyx** [comment]
Yes.
You can double check the format of t1.tsv file as well, which is an example input.
<img width="1090" alt="image" src="https://github.com/GuanLab/FastClone_GuanLab/assets/37345096/caa8ec6a-27f3-4e9b-8863-218790190b15">

**Comment by wt12318** [comment]
Thanks.
