### ISSUE TITLE
AttributeError: module 'fire' has no attribute 'Fire'

### ISSUE THREAD

**Issue by lavale83** [GuanLab/FastClone_GuanLab#3]
When I try to use fastclone, I receive this error:

fastclone --help
Traceback (most recent call last):
  File "/hpcnfs/home/ieo5166/.local/bin/fastclone", line 8, in <module>
    sys.exit(main())
  File "/hpcnfs/home/ieo5166/.local/lib/python3.6/site-packages/fastclone/__main__.py", line 130, in main
    fire.Fire(Entrypoint)
AttributeError: module 'fire' has no attribute 'Fire'

**Comment by Yaoyx** [comment]
Is there any file named "fire.py" in your folder? This might overwrite the "fire package". Or you can try "pip install fire", and see how that works.

**Comment by lavale83** [comment]
I tried "pip install fire" and is not working.
no file fire.py.
it's completely a mistery to me.......

**Comment by Yaoyx** [comment]
Somehow, your fire package is overwritten. Try this, open python in the terminal and try `import fire` and `fire.Fire`. If you get an AttributeError message again, then uninstall the fire package and FastClone, and reinstall them again.

Let me know if this works.

**Comment by lavale83** [comment]
Thank you for your help:
I solved installing fastclone in an empty conda env with python=3.5

**Comment by Yaoyx** [comment]
I see. Conda environment does have overwriting problem sometimes.
