### ISSUE TITLE
Analysis without CNA

### ISSUE THREAD

**Issue by lavale83** [GuanLab/FastClone_GuanLab#4]
How can I manage the analysis without CNA info?

**Comment by Yaoyx** [comment]
I actually don't recommend you do that, as CNA info is necessary for adjusting the variant frequency and getting a more accurate result. 

If you really want to try, you can assume both major and minor CN are 1.

**Comment by lavale83** [comment]
What is meant by minor_cn and major_cn?

**Comment by Yaoyx** [comment]
They stand for minor copy number and major copy number.

**Comment by lavale83** [comment]
Ok, so how can I calculate using for example varscan2? Did you experienced something similar?

**Comment by Yaoyx** [comment]
That requires you to have the original sequence files, and you can use tools like CNVnator or varscan2 to call CNVs. However, usually, it comes with SNV data, which means you can contact the data providers for the CNVs profile.
