### ISSUE TITLE
WISH: Add fastclone --version

### ISSUE THREAD

**Issue by HenrikBengtsson** [GuanLab/FastClone_GuanLab#6]
Please consider adding an option `--version` to query the FastClone version, e.g.

```sh
$ fastclone --version
1.0.5
```

This will help when troubleshooting and for reproducibility.

PS. I'm aware that you can query the version via `pip`.

**Comment by Yaoyx** [comment]
The new feature has been updated now, and the command line is " fastclone version ".
Thank you for your suggestion.

**Comment by HenrikBengtsson** [comment]
Thxs.
