### ISSUE TITLE
Results and the DREAM Challenge?

### ISSUE THREAD

**Issue by HenrikBengtsson** [GuanLab/FastClone_GuanLab#7]
Hi.  Thank you for this method and your nice article 'FastClone is a probabilistic tool for deconvoluting tumor heterogeneity in bulk-sequencing samples', Nature Communications (2020) <http://dx.doi.org/10.1038/s41467-020-18169-2>.

When I read the results section, it's not clear to me is whether or not FastClone participated in the [ICGC-TCGA-DREAM Somatic Mutation Calling Challenge --Tumor Heterogeneity and Evolution](https://www.synapse.org/#!Synapse:syn2813581/wiki/303137) back in 2015/2016.  For example, on https://www.synapse.org/#!Synapse:syn2813581/wiki/303157, I see `5902717 | GuanLab_SMCHet | TestLeaderboard_3 | 2016-04-11` which looks like it could be your entry.  However, that shows upunder 'Pre-submission round' but not under 'Preliminary Leaderboard'.   Now, that says "preliminary" and not "final".  Were there other results later?  

Or, should I interpret it as the final FastClone did not participate in the DREAM Challenge?  Do you use the DREAM Challenge results as a reference/baseline for your results?

Disclaimer: Although I'm aware of DREAM Challenges, this is actually the first time I looked into the details.

**Comment by yuanfangguan** [comment]
Hi Henrik

I will answer this question, while leaving the rest technical questions to students.

FastClone participated in the preliminary, leaderboard and final round of DREAM. For unknown reasons, final round result is not posted other than being shared in the RECOMB-DREAM conference, in which FastClone and another algorithm from Columbia excelled. At one point there was a plan of a paper summarizing the results. But I am unaware of the progress of that paper. 

There is a slight difference between FastClone and original DREAM submission. I wrote the original submission, which was deemed too slow by my students. They rewrote it. We have confirmed consistent results between the two versions despite speed difference. 

Thank you

Yuanfang

**Comment by HenrikBengtsson** [comment]
> FastClone participated in the preliminary, leaderboard and final round of DREAM. For unknown reasons, final round result is not posted other than being shared in the RECOMB-DREAM conference, in which FastClone and another algorithm from Columbia excelled.

Thanks for clarifying this.  And congrats.
