### ISSUE TITLE
is it possible to get cancer cell fraction (CCF)?

### ISSUE THREAD

**Issue by crazyhottommy** [GuanLab/FastClone_GuanLab#8]
Hi, 
Is it possible to get CCF as in pyclone from FastClone?

Thanks!

**Comment by Yaoyx** [comment]
Yes, the command line output message tells you the tumor purity, which indicates the cancer cell fraction. You can also find it in the output file of the subclones--the highest proportion is the tumor purity.

**Comment by crazyhottommy** [comment]
I meant for each mutation, do you output tumor-purity and copy-number adjusted allele frequency. Pyclone calls it CCF.

**Comment by yuanfangguan** [comment]
Original challenge code does: https://github.com/GuanLab/FastClone_GuanLab/tree/master/original_competition_code

But it outputs a lot of redundant info as well.

thank you

**Comment by crazyhottommy** [comment]
Thanks! do you have some instructions on how to use it?

**Comment by yuanfangguan** [comment]
Greetings.

python3 main.py #battenburg file, ## cna file;

thank you

yuanfang
