### ISSUE TITLE
Maximum iteration and convergence issues

### ISSUE THREAD

**Issue by yujie-jiang** [GuanLab/FastClone_GuanLab#9]
Hello, 

When running fastclone, we get the warning message “Maximum iteration reached but the EM did not converge” quite often, and get a final result of only one clone (on more than 50% of the samples we tested, especially on samples with a large number of SNVs). Is this as expected?

We noticed that you set the maximum iteration to 5000, and we also tried to tune that to a much higher number (e.g., 1 million), but seems that it does not really help. The input data format is the same for those that converged vs. those that didn’t (Pyclone format). Do you have any suggestions?

Thank you very much!

**Comment by Yaoyx** [comment]
We also noticed the problem. We will try to fix it.

**Comment by Yaoyx** [comment]
One way that might work for this situation is to adjust the covariance factor of kde function (kde is used in the function '_get_density_peaks' locates in the subclone.py file). The effect of the covariance factor is shown in the supplementary figure 11.

I hope this works for you.

**Comment by yuanfangguan** [comment]
Good afternoon Jeffrey

I will try to give some explanation but it might not be perfect, and would like to hear what you say.

For fastClone, it tends to predict fewer number of clones. We tested it on TCGA collection (which might be what you are doing as well, and obtained the same results). There are other software that tends to predict more clones (i.e. no single clone in the end, or predicts thousands of clones when the number of SNP is large). The difference mainly lies in how one finds the peak. We used a Gaussian-related method, which tends to fuse the peaks. 

The reason we chose this method was primarily because it excelled in the simulated data in the benchmark data. I know it is not a good reason at all. But the fact is, we do not have a ground truth for this type of problem other than simulation. 

As for 5000, as you described, it converges way before 5000, and it only finds one clone in the sample.

thank you

yuanfang

**Comment by Yaoyx** [comment]
**kde.covariance_factor = lambda: .25
    kde._compute_covariance()**

You can add these two lines after line 148 of subclone.py. However, as Dr. Guan mentioned, we don't know the ground truth,  so it's hard to determine the perfect covariance factor.

**Comment by yujie-jiang** [comment]
Hi Dr. Guan and Yao,

Thank you very much for all your speedy responses! I will take a further look and try out the method you suggested~

Best,
Jeffrey

**Comment by sjm5701** [comment]
Hi!

I had a same problem so I followed the direction you suggested but it still doesn't work. Could you look over my attached input data and tell me what's wrong with it? 
I haven't received cnv data yet, so I just put 1 in each major and minor cn for test.

**Comment by yuanfangguan** [comment]
Good morning Sjm5701

![image](https://user-images.githubusercontent.com/28932346/110314615-15c6a180-7fd6-11eb-8f2f-d8bf7e4b9cc5.png)

In this case, I guess KDE merged them into a single significant peak (Yao will run some test and confirm with you). An alternative algorithm may predict several or dozens more clones depending on the resolution they dissect; some examples 1. the presumable peak one at 0.83-0.87, but that will be based on the difference of a single SNP (6 versus 5 at neighboring bins) and will be an over prediction. I do not think it is correct. 2. the presumable peak at 0.18-0.22 shares similar property and if there were indeed a clone, 0.25-0.29 bin should have been much higher. Again, this peak will be based on 3-4 SNP differences. 

We did try to tune some parameters for KDE that could result in more or less clones, but in cases like this where the presumable additional clones are based on small differences of 1-3 SNPs, out of, in this case, 894. FastClone tends to merge them. Some alternatives will predict many, maybe even dozens I believe on this data. 

I guess the key question is how to dissect merged clones, while not over predicting by 1-3 SNP fluctuations. And I do not think there is a good answer yet (or ever).

About adjusting the KDE parameters, apologize for inaccurate description, I think it only affects the results in rare cases. 

thank you

yuanfang

**Comment by Yaoyx** [comment]
> Hi!
> 
> I had a same problem so I followed the direction you suggested but it still doesn't work. Could you look over my attached input data and tell me what's wrong with it?
> I haven't received cnv data yet, so I just put 1 in each major and minor cn for test.
> [fastclone_ssm.txt](https://github.com/GuanLab/FastClone_GuanLab/files/6099619/fastclone_ssm.txt)

Have you tried decreasing the covariance factor? I set it to lambda: .15, and the number of peaks increased to 2. This change reduces the bandwidth of kde, and as a result, the density will be higher (based on the definition of pdf, the area under the curve is the probability of getting the value in an interval, so the smaller bandwidth the higher the density is). Hence, the peaks will be more detectable to FastClone. However, I agree with Dr. Guan's opinion that " it will be an over prediction".

**Comment by sjm5701** [comment]
I got the point. I really appreciate your quick and helpful response.
